version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: lego_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lego_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lego@store1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
